version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: php-fpm

  composer:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
